version: '3.8'

services:
  mongodb:
    image: mongo:latest
    # you can replace the name with any of your own
    container_name: mongodb_kroger
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: backend_kroger
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://admin:password@mongodb:27017/your_db_name?authSource=admin"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
