services:
  backend:
    build: .
    container_name: backend_kroger
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
    command: [ "poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:latest
    container_name: mongodb_kroger
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_kroger
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
