services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_kroger
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  app:
    build: .
    container_name: scraping_app
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"

volumes:
  mongo-data:
