version: '3.8'

services:
  mongodb:
    image: mongo:latest
    # you can replace the name with any of your own
    container_name: mongodb_kroger
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongo-data:
