services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: backend_kroger
    restart: always
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - PYTHONPATH=/app
      - MONGO_URI=mongodb://admin:password@mongodb:27017/your_db_name?authSource=admin

  mongodb:
    image: mongo:latest
    container_name: mongodb_kroger
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
